"""
Agent Builder - toolkit for creating custom Polymarket agents.

Provides programmatic agent generation, template rendering, and
configuration scaffolding for building specialized agents.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

from ms_masa.builder.templates import AgentTemplates
from ms_masa.knowledge.polymarket_kb import PolymarketKB

logger = logging.getLogger(__name__)


class AgentBuilder:
    """Build custom Polymarket agents from templates and specifications."""

    def __init__(self, output_dir: str = "./generated_agents"):
        self.output_dir = Path(output_dir)
        self.templates = AgentTemplates()

    def list_templates(self) -> dict[str, str]:
        """List available agent templates."""
        return AgentTemplates.list_templates()

    def list_agent_patterns(self) -> dict:
        """List architectural patterns for Polymarket agents."""
        return PolymarketKB.AGENT_PATTERNS

    def generate(
        self,
        template: str,
        output_file: Optional[str] = None,
        write: bool = True,
    ) -> str:
        """Generate an agent from a template.

        Args:
            template: Template name (market_monitor, signal_scanner, data_collector, llm_analyst)
            output_file: Optional custom output filename
            write: If True, write to file. If False, return code string only.

        Returns:
            Generated code as string
        """
        template_map = {
            "market_monitor": self.templates.market_monitor,
            "signal_scanner": self.templates.signal_scanner,
            "data_collector": self.templates.data_collector,
            "llm_analyst": self.templates.llm_analyst,
        }

        gen_fn = template_map.get(template)
        if not gen_fn:
            raise ValueError(
                f"Unknown template: {template}. "
                f"Available: {list(template_map.keys())}"
            )

        code = gen_fn()

        if write:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            fname = output_file or f"{template}_agent.py"
            path = self.output_dir / fname
            with open(path, "w") as f:
                f.write(code)
            logger.info("Generated agent: %s", path)

        return code

    def scaffold_project(self, project_name: str, agent_type: str = "read_only_agent") -> dict:
        """Scaffold a complete agent project structure.

        Returns dict mapping file paths to their contents.
        """
        pattern = PolymarketKB.AGENT_PATTERNS.get(
            agent_type, PolymarketKB.AGENT_PATTERNS["read_only_agent"]
        )

        files: dict[str, str] = {}

        # Main agent file
        files[f"{project_name}/agent.py"] = f'''"""
{project_name} - Polymarket Agent
Type: {pattern["description"]}
Requires: {pattern["requires"]}
Generated by Ms-MASA Agent Builder
"""

from ms_masa import MsMasaAgent


class {self._to_class_name(project_name)}:
    """Custom Polymarket agent."""

    def __init__(self):
        self.masa = MsMasaAgent.from_env()

    def run(self):
        """Main agent loop."""
        status = self.masa.status()
        print(f"Agent ready: {{status}}")

        # Your agent logic here
        markets = self.masa.scan_markets(limit=10)
        for m in markets:
            print(f"  {{m['question'][:60]}} | {{m['yes_price']}}")


if __name__ == "__main__":
    agent = {self._to_class_name(project_name)}()
    agent.run()
'''

        # Config file
        files[f"{project_name}/config.json"] = json.dumps({
            "agent": {
                "max_context_tokens": 4096,
                "market_fetch_limit": 100,
                "enable_caching": True,
                "cache_ttl_seconds": 300,
                "log_level": "INFO",
            },
        }, indent=2)

        # Environment template
        files[f"{project_name}/.env.example"] = """# Polymarket Agent Configuration
# Copy to .env and fill in values

# Required for authenticated operations
POLYGON_WALLET_PRIVATE_KEY=

# Required for LLM-powered analysis
OPENAI_API_KEY=

# Optional overrides
# POLYMARKET_CLOB_URL=https://clob.polymarket.com
# POLYMARKET_GAMMA_URL=https://gamma-api.polymarket.com
"""

        # Requirements
        files[f"{project_name}/requirements.txt"] = """ms-masa
httpx>=0.24.0
python-dotenv>=1.0.0
"""

        return files

    def write_scaffold(self, project_name: str, agent_type: str = "read_only_agent") -> list[str]:
        """Write a scaffolded project to disk. Returns list of created files."""
        files = self.scaffold_project(project_name, agent_type)
        created = []
        for rel_path, content in files.items():
            full_path = self.output_dir / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            with open(full_path, "w") as f:
                f.write(content)
            created.append(str(full_path))
        return created

    @staticmethod
    def _to_class_name(name: str) -> str:
        """Convert project name to PascalCase class name."""
        return "".join(word.capitalize() for word in name.replace("-", "_").split("_"))
