"""
Agent code templates for generating Polymarket agents.

Provides ready-to-use code templates for different agent types
that users can customize and deploy.
"""

from __future__ import annotations


class AgentTemplates:
    """Code templates for Polymarket agent generation."""

    @staticmethod
    def market_monitor() -> str:
        """Template: Market monitoring agent."""
        return '''"""
Polymarket Market Monitor Agent
Generated by Ms-MASA Agent Builder
"""

import time
import logging
from ms_masa import MsMasaAgent

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class MarketMonitor:
    """Monitors Polymarket markets for price changes and signals."""

    def __init__(self, poll_interval: int = 60):
        self.agent = MsMasaAgent.from_env()
        self.poll_interval = poll_interval
        self.tracked_markets: dict[str, float] = {}  # market_id -> last_price

    def add_market(self, market_id: str):
        """Add a market to the watch list."""
        self.tracked_markets[market_id] = 0.0

    def check_markets(self) -> list[dict]:
        """Check all tracked markets for changes."""
        alerts = []
        for market_id, last_price in self.tracked_markets.items():
            try:
                analysis = self.agent.analyze_market(market_id)
                current_price = analysis["market"]["yes_price"]
                if last_price > 0:
                    change = current_price - last_price
                    if abs(change) > 0.02:  # 2% threshold
                        alerts.append({
                            "market_id": market_id,
                            "question": analysis["market"]["question"],
                            "price": current_price,
                            "change": change,
                            "signals": analysis.get("signals", []),
                        })
                self.tracked_markets[market_id] = current_price
            except Exception as e:
                logger.warning("Error checking %s: %s", market_id, e)
        return alerts

    def run(self):
        """Start the monitoring loop."""
        logger.info("Market Monitor starting with %d markets", len(self.tracked_markets))
        while True:
            alerts = self.check_markets()
            for alert in alerts:
                logger.info(
                    "ALERT: %s | Price: %.4f | Change: %+.4f",
                    alert["question"][:60], alert["price"], alert["change"],
                )
            time.sleep(self.poll_interval)


if __name__ == "__main__":
    monitor = MarketMonitor(poll_interval=60)
    # Add markets to track by ID
    # monitor.add_market("your-market-id-here")
    # monitor.run()
'''

    @staticmethod
    def signal_scanner() -> str:
        """Template: Signal scanning agent."""
        return '''"""
Polymarket Signal Scanner Agent
Generated by Ms-MASA Agent Builder
"""

import logging
from ms_masa import MsMasaAgent

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class SignalScanner:
    """Scans Polymarket for analytical signals across all markets."""

    def __init__(self):
        self.agent = MsMasaAgent.from_env()

    def full_scan(
        self,
        limit: int = 100,
        spread_threshold: float = 0.05,
        imbalance_threshold: float = 0.3,
    ) -> dict:
        """Run a full signal scan across tradeable markets."""
        signals = self.agent.detect_signals(
            limit=limit,
            spread_threshold=spread_threshold,
            imbalance_threshold=imbalance_threshold,
        )
        summary = {
            "markets_with_signals": len(signals),
            "total_signals": sum(len(s) for s in signals.values()),
            "by_type": {},
        }
        for sigs in signals.values():
            for s in sigs:
                sig_type = s["type"]
                summary["by_type"][sig_type] = summary["by_type"].get(sig_type, 0) + 1

        return {"summary": summary, "signals": signals}

    def scan_category(self, tag: str, limit: int = 50) -> list[dict]:
        """Scan a specific category for interesting markets."""
        markets = self.agent.scan_markets(tag=tag, limit=limit, sort_by="volume")
        interesting = [
            m for m in markets
            if m["certainty"] < 0.8 and m["volume"] > 1000
        ]
        return interesting


if __name__ == "__main__":
    scanner = SignalScanner()
    result = scanner.full_scan(limit=50)
    logger.info("Scan complete: %s", result["summary"])
'''

    @staticmethod
    def data_collector() -> str:
        """Template: Market data collection agent."""
        return '''"""
Polymarket Data Collector Agent
Generated by Ms-MASA Agent Builder
"""

import json
import time
import logging
from pathlib import Path
from datetime import datetime
from ms_masa import MsMasaAgent

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class DataCollector:
    """Collects and stores Polymarket data for analysis."""

    def __init__(self, output_dir: str = "./data"):
        self.agent = MsMasaAgent.from_env()
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def snapshot_all_markets(self) -> str:
        """Take a snapshot of all tradeable markets."""
        markets = self.agent.scan_markets(limit=200, sort_by="volume")
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        filename = f"markets_{timestamp}.json"
        path = self.output_dir / filename
        with open(path, "w") as f:
            json.dump({"timestamp": timestamp, "count": len(markets), "markets": markets}, f)
        logger.info("Saved %d markets to %s", len(markets), path)
        return str(path)

    def track_market_history(self, market_id: str, interval: int = 300, duration: int = 3600):
        """Track a single market over time."""
        history = []
        end_time = time.time() + duration
        while time.time() < end_time:
            try:
                analysis = self.agent.analyze_market(market_id)
                analysis["collected_at"] = datetime.utcnow().isoformat()
                history.append(analysis)
            except Exception as e:
                logger.warning("Collection error: %s", e)
            time.sleep(interval)

        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        path = self.output_dir / f"history_{market_id[:8]}_{timestamp}.json"
        with open(path, "w") as f:
            json.dump(history, f)
        logger.info("Saved %d snapshots to %s", len(history), path)
        return str(path)


if __name__ == "__main__":
    collector = DataCollector()
    collector.snapshot_all_markets()
'''

    @staticmethod
    def llm_analyst() -> str:
        """Template: LLM-powered market analyst agent."""
        return '''"""
Polymarket LLM Analyst Agent
Generated by Ms-MASA Agent Builder

Requires: OPENAI_API_KEY environment variable
"""

import logging
from ms_masa import MsMasaAgent
from ms_masa.knowledge.reference import QuickReference

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class LLMAnalyst:
    """Uses LLM reasoning to analyze Polymarket markets."""

    SYSTEM_PROMPT = """You are a prediction market analyst. Analyze the provided
market data and give a structured assessment. Focus on:
1. Market efficiency (is the price reflecting available information?)
2. Liquidity quality (can positions be entered/exited?)
3. Information signals (what does the order book structure suggest?)
4. Key risks and uncertainties

Be concise and data-driven. This is analytical only, not financial advice."""

    def __init__(self):
        self.agent = MsMasaAgent.from_env()
        self._client = None

    @property
    def llm(self):
        if self._client is None:
            import openai
            self._client = openai.OpenAI()
        return self._client

    def analyze(self, market_id: str) -> str:
        """Produce an LLM-powered analysis of a market."""
        data = self.agent.analyze_market(market_id)
        context = self.agent.get_agent_context("analytical_agent")
        user_msg = f"""Context:\\n{context}\\n\\nMarket Data:\\n{self.agent.compact_json(data)}\\n\\nProvide a structured analysis."""

        response = self.llm.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": user_msg},
            ],
            max_tokens=500,
        )
        return response.choices[0].message.content

    def compare_markets(self, market_ids: list[str]) -> str:
        """Compare multiple markets."""
        data = [self.agent.analyze_market(mid) for mid in market_ids]
        user_msg = f"Compare these markets:\\n{self.agent.compact_json(data)}"

        response = self.llm.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": user_msg},
            ],
            max_tokens=800,
        )
        return response.choices[0].message.content


if __name__ == "__main__":
    analyst = LLMAnalyst()
    # result = analyst.analyze("your-market-id")
    # print(result)
'''

    @staticmethod
    def autonomous_loop() -> str:
        """Template: Autonomous research loop agent."""
        return '''"""
Polymarket Autonomous Loop Agent
Generated by Ms-MASA Agent Builder

An indefinitely-running agent that autonomously iterates:
  1. Scan for opportunities (hypothesis)
  2. Execute analysis (experiment)
  3. Evaluate results against a metric (evaluate)
  4. Keep improvements, discard regressions (decide)
  5. Log results (record)
  6. Repeat forever

Inspired by autonomous research patterns. Designed for
hands-off overnight operation.
"""

import json
import time
import logging
from pathlib import Path
from datetime import datetime
from ms_masa import MsMasaAgent

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class AutonomousLoop:
    """Autonomous agent that continuously scans and analyzes markets."""

    def __init__(
        self,
        cycle_interval: int = 300,
        results_file: str = "results.tsv",
        metric: str = "signal_count",
    ):
        self.agent = MsMasaAgent.from_env()
        self.cycle_interval = cycle_interval
        self.results_path = Path(results_file)
        self.metric = metric
        self.best_score: float = 0.0
        self.cycle = 0

        if not self.results_path.exists():
            self.results_path.write_text(
                "cycle\\ttimestamp\\tmetric\\tscore\\tstatus\\tdescription\\n"
            )

    def scan(self) -> dict:
        """Scout phase: scan markets for opportunities."""
        markets = self.agent.scan_markets(limit=30, sort_by="volume")
        signals = self.agent.detect_signals(limit=30)
        return {
            "markets_scanned": len(markets),
            "markets_with_signals": len(signals),
            "total_signals": sum(len(s) for s in signals.values()),
            "signals": signals,
        }

    def evaluate(self, scan_result: dict) -> float:
        """Evaluate scan results against the configured metric."""
        if self.metric == "signal_count":
            return float(scan_result.get("total_signals", 0))
        elif self.metric == "market_coverage":
            return float(scan_result.get("markets_with_signals", 0))
        return 0.0

    def decide(self, score: float) -> str:
        """Keep or discard based on metric improvement."""
        if score > self.best_score:
            self.best_score = score
            return "keep"
        return "discard"

    def record(self, score: float, status: str, description: str):
        """Log result to TSV file."""
        timestamp = datetime.utcnow().isoformat()
        with open(self.results_path, "a") as f:
            f.write(
                f"{self.cycle}\\t{timestamp}\\t{self.metric}\\t"
                f"{score:.4f}\\t{status}\\t{description}\\n"
            )

    def run(self):
        """LOOP FOREVER: autonomous scan-evaluate-decide cycle."""
        logger.info("Autonomous loop starting. Metric: %s", self.metric)
        logger.info("Results file: %s", self.results_path)

        while True:
            self.cycle += 1
            t0 = time.time()

            try:
                # 1. Scan
                scan_result = self.scan()
                description = (
                    f"scanned {scan_result['markets_scanned']} markets, "
                    f"{scan_result['total_signals']} signals"
                )

                # 2. Evaluate
                score = self.evaluate(scan_result)

                # 3. Decide
                status = self.decide(score)

                # 4. Record
                self.record(score, status, description)

                dt = time.time() - t0
                logger.info(
                    "Cycle %d: score=%.1f status=%s dt=%.1fs | %s",
                    self.cycle, score, status, dt, description,
                )

            except Exception as e:
                logger.error("Cycle %d failed: %s", self.cycle, e)
                self.record(0.0, "crash", str(e))

            # Wait before next cycle
            time.sleep(self.cycle_interval)


if __name__ == "__main__":
    loop = AutonomousLoop(cycle_interval=300)
    loop.run()
'''

    @staticmethod
    def list_templates() -> dict[str, str]:
        """List all available templates with descriptions."""
        return {
            "market_monitor": "Monitors markets for price changes and generates alerts",
            "signal_scanner": "Scans markets for analytical signals (spread, imbalance, liquidity)",
            "data_collector": "Collects and stores market data snapshots over time",
            "llm_analyst": "LLM-powered market analysis using OpenAI",
            "autonomous_loop": "Autonomous loop agent that continuously scans, evaluates, and records results",
        }
